id: 1f1db62c7c6747deacdcbfe9fd0784b2
initial_creation_type: ocr
source_metadata:
  volumes:
    703d33c8b91d43fe92c7f1f631c13820:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: ''
      total_pages: 1953
      volume_number: 27
